export default {
  extends: [
    'stylelint-config-standard-scss',
    'stylelint-config-clean-order',
    '@stylistic/stylelint-config',
  ],
  rules: {
    'no-empty-source': null,
    'selector-class-pattern': null,
    'at-rule-no-unknown': null,
    'no-descending-specificity': null,
    'at-rule-empty-line-before': [
      'always',
      {
        except: ['blockless-after-blockless', 'first-nested'],
        ignore: ['after-comment'],
        ignoreAtRules: ['if', 'else'],
      },
    ],
    'order/properties-order': [
      [
        {
          noEmptyLineBetween: true,
          emptyLineBefore: 'never',
          properties: [
            'all',
            'scroll-behavior',
            'tab-size',
            'content',
            'position',
            'top',
            'right',
            'bottom',
            'left',
            'inset',
            'float',
            'clear',
            'display',
            'order',
            'flex-flow',
            'flex-basis',
            'flex-shrink',
            'flex-grow',
            'flex-wrap',
            'grid',
            'grid-template',
            'grid-template-columns',
            'grid-template-rows',
            'grid-template-areas',
            'grid-area',
            'grid-column',
            'grid-row',
            'grid-column-start',
            'grid-column-end',
            'grid-row-start',
            'grid-row-end',
            'align-content',
            'justify-content',
            'align-items',
            'justify-items',
            'place-content',
            'place-items',
            'place-self',
            'justify-self',
            'align-self',
            'gap',
            'column-gap',
            'row-gap',
            'box-sizing',
            'width',
            'height',
            'min-width',
            'min-height',
            'max-width',
            'max-height',
            'aspect-ratio',
            'margin',
            'margin-inline',
            'margin-block',
            'margin-inline-start',
            'margin-inline-end',
            'margin-block-start',
            'margin-block-end',
            'margin-left',
            'margin-right',
            'margin-top',
            'margin-bottom',
            'padding',
            'padding-inline',
            'padding-block',
            'padding-inline-start',
            'padding-inline-end',
            'padding-block-start',
            'padding-block-end',
            'padding-left',
            'padding-right',
            'padding-top',
            'padding-bottom',
            'list-style-type',
            'color',
            'accent-color',
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'line-height',
            'letter-spacing',
            'word-break',
            'word-spacing',
            'white-space',
            'text-align',
            'text-transform',
            'text-decoration',
            'text-decoration-color',
            'text-decoration-thickness',
            'text-underline-offset',
            'text-size-adjust',
            'text-wrap',
            'text-overflow',
            'text-rendering',
            'text-shadow',
            'text-indent',
            'text-justify',
            'text-outline',
            '-webkit-line-clamp',
            'line-clamp',
            'clip-path',
            'mask',
            'mask-image',
            'mask-position',
            'mask-repeat',
            'mask-size',
            'mask-clip',
            'mask-blend-mode',
            'filter',
            'box-shadow',
            'background',
            'background-color',
            'background-image',
            'background-position',
            'background-repeat',
            'background-size',
            'border',
            'border-top',
            'border-right',
            'border-bottom',
            'border-left',
            'border-top-width',
            'border-right-width',
            'border-bottom-width',
            'border-left-width',
            'border-top-color',
            'border-right-color',
            'border-bottom-color',
            'border-left-color',
            'border-radius',
            'outline',
            'filter',
            'appearance',
            'cursor',
            'object-fit',
            'fill',
            'stroke',
            'perspective',
            'transform',
            'transform-style',
            'transform-origin',
            'translate',
            'rotate',
            'scale',
            'transition',
            'transition-property',
            'transition-duration',
            'transition-timing-function',
            'transition-delay',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',
            'animation-fill-mode',
            'animation-play-state',
            'opacity',
            'will-change',
            'overflow',
            'overflow-x',
            'overflow-y',
            'resize',
            'z-index',
          ],
        },
      ],
      {
        severity: 'warning',
        unspecified: 'ignore',
      },
    ],
    'order/properties-alphabetical-order': null,
    'declaration-block-no-redundant-longhand-properties': [
      true,
      {
        ignoreShorthands: ['transition', 'animation'],
      },
    ],
    'scss/dollar-variable-empty-line-before': null,
    '@stylistic/color-hex-case': 'upper',
    '@stylistic/string-quotes': 'single',
    '@stylistic/block-closing-brace-newline-after': [
      'always',
      {
        ignoreAtRules: ['if', 'else'],
      },
    ],
  },
};
